expense_tracker/expense_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tracker/', include('tracker.urls'))
]

expense_tracker/tracker/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),  # type: ignore
]

expense_tracker/tracker/models.py
from django.db import models


# Create your models here.
class Expense(models.Model):
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=12, decimal_places=2)
    date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-date"]

expense_tracker/tracker/forms.py
from django.forms import ModelForm
from .models import Expense


class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'category']

expense_tracker/tracker/views.py
from django.shortcuts import redirect, render
from django.db.models import Sum
from .models import Expense
from .forms import ExpenseForm
import datetime


# Create your views here.
def index(request):
    if request.method == "POST":
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect("index")

    expenses = Expense.objects.all()
    total_expenses = expenses.aggregate(Sum("amount"))
    form = ExpenseForm()

    # Logic to calculate the total expenses for the year (last 365 days)
    last_year = datetime.date.today() - datetime.timedelta(days=365)
    data_last_year = Expense.objects.filter(date__gt=last_year)
    total_last_year = data_last_year.aggregate(Sum("amount"))

    # Logic to calculate the total expenses for the month (last 30 days)
    last_month = datetime.date.today() - datetime.timedelta(days=30)
    data_last_month = Expense.objects.filter(date__gt=last_month)
    total_last_month = data_last_month.aggregate(Sum("amount"))

    # Logic to calculate the total expenses for the week (last 7 days)
    last_week = datetime.date.today() - datetime.timedelta(days=7)
    data_last_week = Expense.objects.filter(date__gt=last_week)
    total_last_week = data_last_week.aggregate(Sum("amount"))

    # Logic to calculate daily expenses for last 30 days
    daily_expenses = Expense.objects\
        .filter(date__gt=last_month)\
        .values('date')\
        .order_by('date')\
        .annotate(sum=Sum('amount'))

    categorical_expenses = Expense.objects\
        .filter(date__gt=last_month)\
        .values('category')\
        .order_by('category')\
        .annotate(sum=Sum('amount'))

    context = {
        "expenses": expenses,
        "form": form,
        "total_expenses": total_expenses,
        "yearly_sum": total_last_year,
        "monthly_sum": total_last_month,
        "weekly_sum": total_last_week,
        "daily_expenses": daily_expenses,
        "categorical_expenses": categorical_expenses,
    }
    return render(request, "tracker/index.html", context)


def edit(request, id):
    if request.method == "POST":
        expense = Expense.objects.get(id=id)
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
        return redirect("index")

    expense = Expense.objects.get(id=id)
    form = ExpenseForm(instance=expense)  # pre-populate form with expense data
    return render(request, "tracker/edit.html", {"form": form})


def delete(request, id):
    if request.method == "POST" and 'delete' in request.POST:
        expense = Expense.objects.get(id=id)
        expense.delete()
        return redirect("index")

expense_tracker/tracker/templates/tracker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {% block title %}
  <!-- Custom head details goes here -->
  <title>Expense Tracker</title>

  <!-- Custom head details ends here -->
  {% endblock title %}
  <link rel="stylesheet" href="{% static 'tracker/styles.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'tracker/style.css' %}" type="text/css" />
  {% block styles %}
  <!-- Styles goes here -->

  <!-- Styles ends here -->
  {% endblock styles %}
</head>

<body>
  <nav class="shadow-lg p-3">
    <div class="container h-12 flex flex-wrap justify-between items-center mx-auto">
      <a href="#" class="flex">
        <img class="h-10 mr-3" src="{% static 'tracker/images/expense.png' %}" />
        <span class="self-center text-xl font-bold text-gray-700">Expense Tracker</span> 
      </a>
    </div>
  </nav>


  {% block body %}
  <!-- Body starts here -->

  <!-- Body ends here -->
  {% endblock body %}

  {% block scripts %}
  <!-- Script goes here -->

  <!-- Script ends here -->
  {% endblock scripts %}
</body>

</html>

expense_tracker/tracker/templates/tracker/edit.html
{% extends "tracker/base.html" %}
<!-- Body starts here. -->
{% block body %}
<div class="w-2/3 h-[700px] mt-10 m-auto bg-gray-100 p-5 rounded-xl">
  <h2 class="text-xl font-bold text-gray-600 text-center">💰 Expense Details</h2>
  <form action="" method="post" class="shadow-lg m-10 p-3 rounded-lg bg-gray-200">
    {% csrf_token %}
    <div class="form container px-5 py-5 flex">
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_name">Expense Name</label>
        </div>
        <div>{{ form.name }}</div>
      </div>
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_amount">Cost</label>
        </div>
        <div>{{ form.amount }}</div>
      </div>
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_category">Category</label>
        </div>
        <div>{{ form.category }}</div>
      </div>
      <div class="mx-10">
        <input
          class="bg-green-600 px-3 py-2 mt-7 rounded-md text-white font-bold"
          type="submit"
          value="Edit Data"
        />
      </div>
    </div>
    <div class="error container text-red-500 px-8">
      {% if form.errors %} {% for field in form %} {% for error in field.errors %}
      <p class="text-red-500 text-base">{{ error }}</p>
      {% endfor %} {% endfor %} {% endif %}
    </div>
  </form>
</div>
<!-- Body ends here. -->
{% endblock body %}

expense_tracker/tracker/templates/tracker/index.html
{% extends "tracker/base.html" %}
{% load humanize %}
<!-- Example of using super in template inheritance -->
{% block title %} {{ block.super }} {% endblock title %}
<!-- End of Example -->

<!-- Body starts here -->
{% block body %}
<div class="w-2/3 h-[700px] mt-10 m-auto bg-gray-100 p-5 rounded-xl">
  <h2 class="text-xl font-bold text-gray-600 text-center">💰 Add Expense ➕</h2>
  <form action="" method="post" class="shadow-lg m-10 p-3 rounded-lg bg-gray-200">
    {% csrf_token %}
    <div class="form container px-5 py-5 flex">
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_name">Expense Name</label>
        </div>
        <div> {{ form.name }} </div>
      </div>
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_amount">Cost</label>
        </div>
        <div>
          {{ form.amount }}
        </div>
      </div>
      <div class="mb-3 mx-10">
        <div class="mr-3 mb-3 text-lg font-semibold">
          <label for="id_category">Category</label>
        </div>
        <div>
          {{ form.category }}
        </div>
      </div>
      <div class="mx-10"><input class="bg-green-600 px-3 py-2 mt-7 rounded-md text-white font-bold" type="submit"
               value="Submit" /></div>
    </div>
    <div class="error container text-red-500 px-8">
      {% if form.errors %}
      {% for field in form %}
      {% for error in field.errors %}
      <p class="text-red-500 text-base">{{ error }}</p>
      {% endfor %}
      {% endfor %}
      {% endif %}
    </div>

  </form>

</div>
<div class="h-5 w-2/3 m-auto"></div>
<div class="w-2/3 m-auto bg-gray-100 p-10 rounded-xl">

  <div>
    <h3 class="text-2xl text-gray-700 font-semibold text-center mb-4">Expenses</h3>
  </div>
  <div class="shadow-lg rounded-lg px-7 bg-gray-200">
    <div class="expense-header flex flex-wrap px-20 py-3">
      <span>Name</span>
      <span>Amount</span>
      <span>Category</span>
      <span>Date</span>
      <span>Edit</span>
      <span>Delete</span>
    </div>
    <hr class="bg-black w-full h-0.5">
    {% for expense in expenses %}
    <div class="expense-row flex flex-wrap px-20 py-3">
      <span class="font-semibold">{{ expense.name }}</span>
      <span class="font-semibold">&#8377; {{ expense.amount|intcomma }}</span>
      <span class="font-semibold">{{ expense.category }}</span>
      <span class="font-semibold">{{ expense.date }}</span>
      <span class="font-semibold">
        <a class="bg-yellow-700 px-4 py-2 rounded-md text-white text-sm font-bold"
           href="{% url 'edit' expense.id %}">Edit</a>
      </span>
      <span class="font-semibold">
        <form action="{% url 'delete' expense.id %}" method="post">
          {% csrf_token %}
          <input class="bg-red-600 px-2 py-2 rounded-md text-white text-sm font-bold" type="submit" value="Delete"
                 name="delete" />
        </form>
      </span>
    </div>
    {% endfor %}
    <hr class="bg-gray-800 w-full h-0.5">
    <div class="expense-row flex flex-wrap px-20 py-3">
      <span></span>
      <span class="font-bold text-green-500">Total: &#8377; {{total_expenses.amount__sum|intcomma }}</span>
      <span></span>
      <span></span>
      <span></span>
      <span></span>
    </div>

  </div>
</div>
<div class="h-5 w-2/3 m-auto"></div>
<div class="w-2/3 m-auto bg-gray-100 p-10 rounded-xl flex space-x-8">
  <div class="w-1/3 shadow-lg bg-gray-200 rounded-lg">
    <h1 class="ml-12 py-2 font-bold text-gray-700">Last 365 Days</h1>
    <h1 class="ml-12 py-1 text-2xl font-bold text-green-600">
      &#8377; {{ yearly_sum.amount__sum|intcomma }}
    </h1>
  </div>
  <div class="w-1/3 shadow-lg bg-gray-200 rounded-lg">
    <h1 class="ml-12 py-2 font-bold text-gray-700">Last 30 Days</h1>
    <h1 class="ml-12 py-1 text-2xl font-bold text-green-600">
      &#8377; {{ monthly_sum.amount__sum|intcomma }}
    </h1>
  </div>
  <div class="w-1/3 shadow-lg bg-gray-200 rounded-lg">
    <h1 class="ml-12 py-2 font-bold text-gray-700">Last 7 Days</h1>
    <h1 class="ml-12 py-1 text-2xl font-bold text-green-600">
      &#8377; {{ weekly_sum.amount__sum|intcomma }}
    </h1>
  </div>
</div>

<div class="h-5 w-2/3 m-auto"></div>
<div class="w-2/3 m-auto bg-gray-100 p-10 rounded-xl">
  <h3 class="text-2xl text-gray-700 font-semibold text-center py-3">Past 30 Days</h3>
  <div class="flex space-x-8">
    <div class="w-1/2 rounded-lg bg-gray-200 shadow-lg m-10 pb-5">
      <div class="flex flex-wrap space-x-40 text-gray-700 text-lg font-bold px-20 py-5">
        <span> Daily Expenses </span>
      </div>
      <hr class="h-0.5 bg-black">
      <div id="30-day-table">
        {% for daily_expense in daily_expenses %}
        <div class="flex flex-wrap px-20 pt-5 font-semibold">
          <span> {{ daily_expense.date }} </span>
        </div>
        <div class="flex flex-wrap px-20 pt-5">
          <span class="text-green-600 font-semibold">&#8377; {{ daily_expense.sum|intcomma }} </span>
        </div>
        {% endfor %}
      </div>
    </div>

    <div class="w-1/2 rounded-lg bg-gray-200 shadow-lg m-10 pb-5">
      <div class="flex flex-wrap space-x-40 font-bold text-gray-700 text-lg px-20 py-5">
        <span> Expenses By Categories </span>
      </div>
      <hr class="h-0.5 bg-black">
      <div id="categorical-expense">
        {% for category in categorical_expenses %}
        <div class="flex flex-wrap px-20 pt-5 font-semibold">
          <span> {{ category.category }} </span>
        </div>
        <div class="flex flex-wrap px-20 pt-3">
          <span class="text-green-600 font-semibold">&#8377; {{ category.sum|intcomma }} </span>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>


<div class="h-5 w-2/3 m-auto"></div>
<div class="w-2/3 m-auto bg-gray-100 p-10 rounded-xl">
  <h3 class="text-2xl text-gray-700 font-semibold text-center py-3">Past 30 Days</h3>
  <div class="flex space-x-8">
    <div class="w-1/2 shadow-lg ml-10 bg-gray-200">
      <h1 class="text-xl font-semibold text-center py-7">Expense spread across categories</h1>
      <canvas id="categoryChart" class="m-10"></canvas>
    </div>

    <div class="w-1/2 shadow-lg ml-10 bg-gray-200">
      <h1 class="text-xl font-semibold text-center py-7">Daily Expenses</h1>
      <canvas id="dailyChart" class="m-10"></canvas>
    </div>
  </div>
</div>
<!-- body ends here -->
<div class="h-20 w-2/3 m-auto"></div>
{% endblock body %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"></script>

<script>
  // Categorical Expenses Calculations
  const categories = [];
  const sumByCategories = [];

  const dates = [];
  const sumByDate = [];

  const catSumDiv = document.getElementById('categorical-expense').getElementsByTagName('div');
  // console.log(catSumDiv);
  for(let i = 0; i < catSumDiv.length; i++) {
    // Since arrays start from 0, even indices are categories and odd indices are sums
    if (i % 2 == 0) {
      categories.push(catSumDiv[i].innerText);
    } else {
      let price = catSumDiv[i].innerText;
      price = price.replace(/,/g, '');
      price = price.split(' ')[1];
      price = parseFloat(price);
      sumByCategories.push(price);
    }
  }

  const dailySumDiv = document.getElementById('30-day-table').getElementsByTagName('div');
  // console.log(dailySumDiv);
  for(let i = 0; i < dailySumDiv.length; i++) {
    // Since arrays start from 0, even indices are categories and odd indices are sums
    if (i % 2 == 0) {
      dates.push(dailySumDiv[i].innerText);
    } else {
      let price = dailySumDiv[i].innerText;
      price = price.replace(/,/g, '');
      price = price.split(' ')[1];
      price = parseFloat(price);
      sumByDate.push(price);
    }
  }

  console.log(dates);
  console.log(sumByDate);
  // Graph
  window.onload = function () {
    let ctx = document.getElementById('categoryChart').getContext('2d');
    let myChart = new Chart(ctx, {
      type: 'pie',
      data: {
        labels: categories,
        datasets: [{
          label: 'Expense By Categories',
          data: sumByCategories,
          borderWidth: 1,
        }]
      }
    });

    // Daily Expenses Chart
    let ctx2 = document.getElementById('dailyChart').getContext('2d');
    let myChart2 = new Chart(ctx2, {
      type: 'line',
      data: {
        labels: dates,
        datasets: [{
          label: 'Daily Expenses',
          data: sumByDate,
          borderWidth: 1,
        }]
      }
    });
  };
</script>


{% endblock scripts %}